### ISSUE TITLE
some questions in the paper

### ISSUE THREAD

**Issue by liyuanyaun** [sciencefans/RSA-for-object-detection#2]
(1)in RSA section of your paper, i do not understand This paragraph："During inference, we first have the possible scales of the input from the scale-forecast network. The image is then resized accordingly to the extent that the smallest scale (corresponding to the largest feature map) is resized to the range of [64; 128]."
is  "the smallest scale" of faces or image? and do you mean that resize operation is to ensure "the smallest scale" in the range of [64; 128].?

(2)for Scale forecast Network in figure 3 of you paper, when it output 28 in [20,30] which means the size of face is in the range of [128,256], corresponding m is equal to 2. this means after RSA, the size of the face is in range of [32,64]. and when it output 35 in [30,40] which means the size of is in the range of [256,512], corresponding m is equal to 3. this means after RSA, the size of the face is in range of [32,64],too. so RSA is to ensure the size of face  in the range of  [32,64]?

look forward your answers, thanks!

**Comment by liuyuisanai** [comment]
Hi @liyuanyaun ,

(1) Yes. Let's assume there are three faces with size of 100,200 and 500 in one image with the length of 1000. For inference, we resize the length of image to 1000 * 64*sqrt(2) / 100.

(2) It seems there's a misunderstanding. Could you please leave me an email address so that I can send you our supplementary which contains a detailed example.

**Comment by liyuanyaun** [comment]
hi, thank you for your answering. my email address is liyuanyaunmath@163.com. thank you very much

**Comment by liuyuisanai** [comment]
Sorry, an error occurred:

> 550 User not found: liyuanyaunmath@163.com
> Final-Recipient: rfc822; liyuanyaunmath@163.com
> Action: failed
> Status: 5.0.0
> Remote-MTA: dns; 163mx02.mxmail.netease.com. (43.230.90.6, the server for the
>  domain 163.com.)
> Diagnostic-Code: smtp; 550 User not found: liyuanyaunmath@163.com
> Last-Attempt-Date: Sat, 30 Sep 2017 02:33:48 -0700 (PDT)

Do you have another address?

**Comment by liyuanyaun** [comment]
sorry,my mistake, my email address is liyuanyuanmath@163.com, sorry again

**Comment by shz0519** [comment]
hi,@sciencefans ,@liyuanyaun Could you please send me the supplementary which contains a detailed example.my email address is shz_0519@126.com. thank you very much

**Comment by liyuanyaun** [comment]
ok

**Comment by ElegantGod** [comment]
hi,@sciencefans @liyuanyaun Could you please send me the supplementary which contains a detailed example.my email address is 838060390@qq.com. thank you very much

**Comment by liyuanyaun** [comment]
ok

**Comment by SyGoing** [comment]
hello, could you please  Could you please send me the supplementary which contains a detailed example ? my email address is 963298491@qq.com. thank you very much

**Comment by SyGoing** [comment]
@ElegantGod @liyuanyaun hello, could you please Could you please send me the supplementary which contains a detailed example ? my email address is 963298491@qq.com. thank you very much
